---
title: "Project 3 - Data Cleaning"
author: "Max Lippman, Marti Walstad, Jenna Sayle, Alaina Edwards"
format: 
  html:
    toc: true
    toc-location: left
    toc-expand: true
    code-tools: true 
    code-fold: true
    code-overflow: scroll
    self-contained: true
editor: 
  markdown: 
    wrap: 72
---

## Session Information
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if(require(pacman)==FALSE) install.packages("pacman")
pacman::p_load(#DataExplorer, # For explorer and cleaning data by visualizing missing values.
               gptstudio,#For coding assistance
               httr, # For downloading the data from the UCI
               tidyverse, # For data manipulation
               sjPlot, 
               corrplot, # for heatmaps
               DataExplorer, #for exploring data
               skimr, # for nice summary of data
               readxl,
               dplyr
               ) # For creating dummy variables of categorical variables automatically.)
```

```{r}
sessionInfo()
```

## Import and Merge FIles
```{r}
# Read in Attributes File and drop column
studentinfo <- read.csv("Attributes.csv")
studentinfo = studentinfo %>% select(-`X`)

## Read in BA_Majors.csv and drop column
studentlist <- read.csv("BA_Majors.csv")
studentlist = studentlist %>% select(-`X`)

# Combine the two data frames
merged_data <- merge(studentinfo, studentlist, by = c("Student.ID", "Term.Code"))
```


```{r}
minors <- read_excel("BA Major Students - Minors.xlsx")
minors <- minors %>% rename(Student.ID = `Student ID`, Term.Code = `Term Code`, Cohort.Term = `Cohort Term`)
minors = minors %>% select(-`Enrolled Student Count`)

merged_data <- merge(merged_data, minors, by = c("Student.ID", "Term.Code"), all.x = TRUE, all.y = TRUE)
merged_data = merged_data %>% select(-`Cohort.Term.y`)

```

```{r}
thematic <- read_excel("BA Major Students - Thematic Sequence ISA2.xlsx")
thematic <- thematic %>% rename(Student.ID = `Student ID`, Term.Code = `Term Code`, Thematic.Sequence.Title = `Thematic Sequence Title`)
thematic = thematic %>% select(-`Enrolled Student Count`)

merged_data_1 <- merge(merged_data, thematic, by = c("Student.ID", "Term.Code"), all.x = TRUE, all.y = TRUE)
```

```{r}
#merged_with_flag <- merged_data %>% group_by(Student.ID) %>% filter (!( last(!(Major.1 == 'BA Major' | Major.2 == 'BA Major' | Major.3 == 'BA Major' |Minor == 'Business Analytics' | Thematic.Sequence.Title == 'ISA2 Applied Business Statistics'))))
```

```{r}
merged_drop_last_2 <- merged_data_1 %>%
  group_by(Student.ID) %>%
  filter(!(last(Major.1 != 'BA Major' & Major.2 != 'BA Major' & Major.3 != 'BA Major' & Minor != 'Business Analytics' & Thematic.Sequence.Title != 'ISA2 Applied Business Statistics', order_by = Term.Code) & row_number() == n()))

```

```{r}
#merged_with_flag <- merged_data %>% group_by(Student.ID) %>% slice(-n()) %>%ungroup() %>% filter(!(last((Major.1 == 'BA Major' | Major.2 == 'BA Major' | Major.3 == 'BA Major' | Minor == 'Business Analytics' | Thematic.Sequence.Title == 'ISA2 Applied Business Statistics'))))
```

```{r}
#merged_with_flag <- merged_data %>% group_by(Student.ID) %>% filter(row_number() < n()) %>%ungroup() %>%filter(!last(Major.1 == 'BA Major' | Major.2 == 'BA Major' | Major.3 == 'BA Major' | Minor == 'Business Analytics' | Thematic.Sequence.Title == 'ISA2 Applied Business Statistics', order_by = Term.Code))
```

```{r}
merged_with_flag_3 <- merged_drop_last_2 %>% group_by(Student.ID) %>% mutate (Flag = ifelse(n() < 8 & tail(Term.Code, 1) != '202410', 1,0)) %>% ungroup()
```

```{r}
flagged_true_4 = merged_with_flag_3 %>% filter(Flag == 1)
```

```{r}
write.csv(merged_data, file = 'Student_Data_without_grades')
```

```{r}
grades <- read_csv("Grades.csv")
grades = grades %>% select(-`...1`, -`GPA Quality Points`, -`Final Letter Grade`)
grades <- grades %>% rename(Student.ID = `Student ID`, Term.Code = `Term Code`, `Final Letter Grade Group` = `Final Letter Grade Group`)

merged_with_flag_and_grades <- merge(merged_with_flag_3, grades, by = c("Student.ID", "Term.Code"), all.x = TRUE, all.y = TRUE)

merged_with_flag_and_grades <- merged_with_flag_and_grades %>% rename(Cohort.Term = `Cohort.Term.x`)
merged_with_flag_and_grades = merged_with_flag_and_grades %>% select(-`Earned Academic Credit`)
```

```{r}
count_table <- merged_data %>%
  group_by(Term.Code) %>%
  summarise(DistinctStudentCount = n_distinct(Student.ID))

# Print the new table
print(count_table)
```

```{r}
saveRDS(merged_data, 'Project3_StudentData')
write.csv(merged_data, file = 'Student Data')
```

